"""empty message

Revision ID: 0c0da6308d3f
Revises: 598764f71175
Create Date: 2024-01-25 01:44:03.774648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0da6308d3f'
down_revision = '598764f71175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_status', sa.Enum('0', '1'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('report_status')

    # ### end Alembic commands ###
