"""empty message

Revision ID: 0e141bc65e90
Revises: b36ffbab9319
Create Date: 2024-02-13 21:18:27.583231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e141bc65e90'
down_revision = 'b36ffbab9319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_msg', sa.Text(), nullable=False))
        batch_op.drop_column('fedback_msg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fedback_msg', mysql.TEXT(), nullable=False))
        batch_op.drop_column('feedback_msg')

    # ### end Alembic commands ###
