"""empty message

Revision ID: 27e88e327a5c
Revises: 0c0da6308d3f
Create Date: 2024-01-27 18:46:53.742587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27e88e327a5c'
down_revision = '0c0da6308d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('message_user1_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_user2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_content', mysql.TEXT(), nullable=False),
    sa.Column('message_created_on', mysql.DATETIME(), nullable=True),
    sa.Column('message_updated_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_user1_id'], ['user.user_id'], name='message_ibfk_1'),
    sa.ForeignKeyConstraint(['message_user2_id'], ['user.user_id'], name='message_ibfk_2'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
