"""empty message

Revision ID: 29b69f735fc8
Revises: c278a96f5763
Create Date: 2024-01-30 18:51:35.963188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b69f735fc8'
down_revision = 'c278a96f5763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comment_report_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_desc', mysql.TEXT(), nullable=False),
    sa.Column('comment_datetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_report_id'], ['report.report_id'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['comment_user_id'], ['user.user_id'], name='comment_ibfk_2'),
    sa.PrimaryKeyConstraint('comment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
