"""empty message

Revision ID: 5006f422dcc7
Revises: 85404aa3af13
Create Date: 2024-01-22 23:14:08.108320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5006f422dcc7'
down_revision = '85404aa3af13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_hide_user', sa.Enum('on'), nullable=True))
        batch_op.drop_column('report_identity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_identity', mysql.ENUM('0', '1'), nullable=True))
        batch_op.drop_column('report_hide_user')

    # ### end Alembic commands ###
