"""empty message

Revision ID: 598764f71175
Revises: c2fa6385ca7d
Create Date: 2024-01-25 01:43:43.821470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '598764f71175'
down_revision = 'c2fa6385ca7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('report_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_status', mysql.ENUM('0', '1'), nullable=True))

    # ### end Alembic commands ###
