"""empty message

Revision ID: 642c3a981cbf
Revises: e11d85a68332
Create Date: 2024-02-13 05:59:44.603847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642c3a981cbf'
down_revision = 'e11d85a68332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_otp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_otp')

    # ### end Alembic commands ###
