"""empty message

Revision ID: 6ac019f55163
Revises: 6cbcd7d2cad1
Create Date: 2024-02-12 10:41:35.794477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac019f55163'
down_revision = '6cbcd7d2cad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_name', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_services', schema=None) as batch_op:
        batch_op.drop_column('featured_name')

    # ### end Alembic commands ###
