"""empty message

Revision ID: 7f2771d0e79c
Revises: a17654a69d30
Create Date: 2024-01-31 14:19:15.847622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2771d0e79c'
down_revision = 'a17654a69d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('like_report_id', sa.Integer(), nullable=True),
    sa.Column('like_user_id', sa.Integer(), nullable=True),
    sa.Column('like_status', sa.Integer(), nullable=True),
    sa.Column('like_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['like_report_id'], ['report.report_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
