"""empty message

Revision ID: 85404aa3af13
Revises: 92621aef0912
Create Date: 2024-01-22 20:20:28.129203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85404aa3af13'
down_revision = '92621aef0912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_status', sa.Enum('0', '1'), nullable=True))
        batch_op.add_column(sa.Column('report_identity', sa.Enum('0', '1'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('report_identity')
        batch_op.drop_column('report_status')

    # ### end Alembic commands ###
