"""empty message

Revision ID: 93b52ae967af
Revises: 27e88e327a5c
Create Date: 2024-01-27 18:48:02.213275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b52ae967af'
down_revision = '27e88e327a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_user1_id', sa.Integer(), nullable=False),
    sa.Column('message_user2_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_created_on', sa.DateTime(), nullable=True),
    sa.Column('message_updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_user1_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['message_user2_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
