"""empty message

Revision ID: b36ffbab9319
Revises: 642c3a981cbf
Create Date: 2024-02-13 18:48:41.047559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36ffbab9319'
down_revision = '642c3a981cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_user_id', sa.Integer(), nullable=False),
    sa.Column('fedback_msg', sa.Text(), nullable=False),
    sa.Column('feedback_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
