"""empty message

Revision ID: c2fa6385ca7d
Revises: 5006f422dcc7
Create Date: 2024-01-25 00:19:58.644098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fa6385ca7d'
down_revision = '5006f422dcc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.Enum('0', '1'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_status')

    # ### end Alembic commands ###
