"""empty message

Revision ID: ecc8ebe41424
Revises: 
Create Date: 2024-02-05 18:20:53.735029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc8ebe41424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_contact',
    sa.Column('quick_contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quick_contact_name', sa.String(length=80), nullable=False),
    sa.Column('quick_contact_email', sa.String(length=60), nullable=False),
    sa.Column('quick_contact_message', sa.Text(), nullable=False),
    sa.Column('quick_contact_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('quick_contact_id')
    )
    op.create_table('report_category',
    sa.Column('report_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_category_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('report_category_id')
    )
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('usertype',
    sa.Column('usertype_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usertype_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('usertype_id')
    )
    op.create_table('lga',
    sa.Column('lga_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lga_name', sa.String(length=100), nullable=False),
    sa.Column('lga_state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lga_state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('lga_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=30), nullable=False),
    sa.Column('user_lname', sa.String(length=30), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_pwd', sa.String(length=255), nullable=False),
    sa.Column('user_gender', sa.Enum('male', 'female'), nullable=False),
    sa.Column('user_picture', sa.String(length=30), nullable=True),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('user_desc', sa.Text(), nullable=True),
    sa.Column('user_address', sa.Text(), nullable=True),
    sa.Column('user_opr_hours', sa.Text(), nullable=True),
    sa.Column('user_website', sa.String(length=50), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('user_lga_id', sa.Integer(), nullable=True),
    sa.Column('user_state_id', sa.Integer(), nullable=True),
    sa.Column('user_status', sa.Enum('0', '1'), nullable=True),
    sa.Column('user_date_reg', sa.DateTime(), nullable=True),
    sa.Column('user_profile_lastedit', sa.DateTime(), nullable=True),
    sa.Column('user_last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_lga_id'], ['lga.lga_id'], ),
    sa.ForeignKeyConstraint(['user_state_id'], ['state.state_id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['usertype.usertype_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_user1_id', sa.Integer(), nullable=False),
    sa.Column('message_user2_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_created_on', sa.DateTime(), nullable=True),
    sa.Column('message_updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_user1_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['message_user2_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_user_id', sa.Integer(), nullable=True),
    sa.Column('report_category_id', sa.Integer(), nullable=True),
    sa.Column('report_location', sa.String(length=255), nullable=True),
    sa.Column('report_desc', sa.Text(), nullable=False),
    sa.Column('report_file_name', sa.String(length=100), nullable=True),
    sa.Column('report_status', sa.Enum('0', '1'), nullable=True),
    sa.Column('report_hide_user', sa.Enum('on'), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('report_lastedit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_category_id'], ['report_category.report_category_id'], ),
    sa.ForeignKeyConstraint(['report_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_report_id', sa.Integer(), nullable=True),
    sa.Column('comment_user_id', sa.Integer(), nullable=True),
    sa.Column('comment_desc', sa.Text(), nullable=False),
    sa.Column('comment_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_report_id'], ['report.report_id'], ),
    sa.ForeignKeyConstraint(['comment_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('like',
    sa.Column('like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('like_report_id', sa.Integer(), nullable=True),
    sa.Column('like_user_id', sa.Integer(), nullable=True),
    sa.Column('like_status', sa.Integer(), nullable=True),
    sa.Column('like_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['like_report_id'], ['report.report_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('report')
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('lga')
    op.drop_table('usertype')
    op.drop_table('state')
    op.drop_table('report_category')
    op.drop_table('quick_contact')
    # ### end Alembic commands ###
